### PR TITLE
[BUG] Fix Memory leaks related to the occluded content elements

### PR DESCRIPTION
**Pull request by cyril-sf**

### CODE REVIEW

**Comment by cyril-sf** [comment]
I haven't looked yet at the tests to see if there's a good way to check it or if we think it's good as it is.

**Comment by cyril-sf** [comment]
Not sure why the tests are failing for `ember-release` and `ember-beta`, I'll investigate.

**Comment by cyril-sf** [comment]
Tests are passing locally for `ember-release`. I wonder if the failure is because of the log being too long

Screen Shot 2019-04-23 at 8 51 44 AM

**Comment by cyril-sf** [comment]
I opened another PR ( #256 ) to fix first the build.

**Comment by cyril-sf** [comment]
@runspired @pzuraq Can you take a look?

**Comment by pzuraq** [comment]
Hmm, looks like this can merged without a rebase, looks good!

**Comment by cyril-sf** [comment]
@pzuraq thanks!

**Comment by pzuraq** [comment]
No prob! Let me know if/when y'all need a new beta to be cut, if you have any other changes planned we can wait on those, if not I can publish as soon as I can get master green (could be flakiness)

**Comment by cyril-sf** [comment]
Master is red I believe for a similar problem that I solved: the log gets too big.

Screen Shot 2019-04-24 at 5 57 02 PM

```

**Comment by cyril-sf** [comment]
I tracked down the issue in `ember-test-helpers` (See emberjs/ember-test-helpers#546), released in 1.3.1.

`ember-qunit` updated its version of `ember-test-helpers in 4.3.0 (See emberjs/ember-qunit#434)

`ember-cli-qunit` is deprecated in favor of `ember-qunit`

**Comment by cyril-sf** [comment]
#259 to track progress

**Pull request merged**
