### PR TITLE
Fix build for 4.0

### LINKED ISSUE #393: Transpiling error in Ember 4 without embroider
The below only happens when not using embroider.

Line 352 of radar.js
```
    assert('Must provide a `estimateHeight` value to vertical-collection', estimateHeight !== null);
```
is being transpiled to
```
      (!(estimateHeight !== null) && Ember.assert('Must provide a `estimateHeight` value to vertical-collection', estimateHeight !== null));
```
This causes the error `Ember is not defined` 

[package.json](https://github.com/html-next/vertical-collection/files/9952854/package.json.txt)

### PR DESCRIPTION
**Pull request by wagenet**
Fixes #393.

...or at least attempts to!

### CODE REVIEW

**Comment by mixonic** [comment]
FYI CI on the repo is very bad. I may need to rerun failures to get then green, if they don't look related.

**Comment by runspired** [comment]
Best I can tell CI failures are unrelated for most of the versions but we may have broken 3.12/3.16/3.20

**Comment by mixonic** [comment]
Uh. I hope we did not? Those versions are supported and the support is used by ember table and apps I work on.

**Comment by runspired** [comment]
@mixonic you missed I added a commit to fix them

**Comment by mixonic** [comment]
Ah, amazing. Thanks @runspired @wagenet !

**Pull request merged**
