### PR TITLE
Manual scrolling (updating idForFirstItem). Issue #162

### PR DESCRIPTION
**Pull request by ahamedalthaf**
Manual scrolling (updating idForFirstItem). Issue #162

**Usage:**

template:
       {{vertical-collection registerAPI=(action "registerAPI")}}

Component:
       export default Component.extend({
        actions: {
          registerAPI(api) {
              this.set('collectionAPI', api);
          }
        },
        scrollToItem() {
          let collectionAPI = this.get('collectionAPI');
          collectionAPI.scrollToItem(index);
        }
      });

### CODE REVIEW

**Comment by pzuraq** [comment]
@ahamedalthaf this looks good overall! We need to add some basic tests, and get the current tests passing, but I would be ok with merging once that's done!

**Comment by NullVoxPopuli** [comment]
Is this something that could be used to, after a render -- maybe you're scrolled to the bottom of the list --  allow you to programatically scroll to the top?

**Comment by pzuraq** [comment]
Yes, it would allow that

**Comment by candunaj** [comment]
Hi, is the registerAPI mentioned somewhere in documentation?

**Comment by lolmaus** [comment]
@ahamedalthaf Can you please finalize this?

Rebase, fix existing tests & add a new test?

🙏

**Comment by ahamedalthaf** [comment]
> > @ahamedalthaf Can you please finalize this?
> > Rebase, fix existing tests & add a new test?
> > 🙏
> 
> Not able to allocate time. Will try to allocate some time for this.

Fixed the test cases and added a new test case for the public API

**Comment by ahamedalthaf** [comment]
@runspired @pzuraq @rwwagner90 Can you guys please check this PR once.
This should fix below issues
https://github.com/html-next/vertical-collection/issues/316
https://github.com/html-next/vertical-collection/issues/212
https://github.com/html-next/vertical-collection/issues/158

**Comment by pzuraq** [comment]
I'm not longer maintaining this library

**Comment by rwwagner90** [comment]
Looks like @runspired approved this awhile back, so I will merge.

**Comment by mixonic** [comment]
In `3.0.0-1`

**Pull request merged**
