### PR TITLE
automate changelog generation

### PR DESCRIPTION
**Pull request by efx**
Use https://github.com/rwjblue/create-rwjblue-release-it-setup for a
release-it setup.
Addressing https://github.com/html-next/vertical-collection/issues/288#issuecomment-521998860
I've not run the changelog generation yet. Once agreed upon and merged we could do that in a separate PR.

### CODE REVIEW

**Comment by rwwagner90** [comment]
@efx I would prefer github_changelog_generator or something that uses tags on issues and PRs to generate the changelog.

**Comment by efx** [comment]
Sure. lerna-changelog does use tags on the PRs so I'm not sure I understand the objection. You can see it at work here: https://github.com/adopted-ember-addons/ember-pikaday

**Comment by rwwagner90** [comment]
@efx I didn't see anything about lerna here. I'm unfamiliar with release-it but when I quickly read their changelog section, I didn't see anything about using lerna or tags.

**Comment by efx** [comment]
@rwwagner90  no worries; I think part of its name (`lerna`) gives the wrong impression. I chose it because of recommendations in adopted addons discussion and I found it useful to generate the changelog based on labels. I also chose it because of the automated release it setup. 
I'm totally fine with whatever direction you want to head; contributing-wise I opted for the laziest approach I know.

**Comment by rwwagner90** [comment]
@efx if this uses tags, I am not opposed to it. @pzuraq what is used for the other Ember projects for changelogs? Is it still a custom script?

**Comment by efx** [comment]
Woot! I'm opting for whatever is standard across ember projects and is the path of least resistance.

**Comment by rwwagner90** [comment]
Not sure there is a defined standard. I think Ember uses some custom scripts. I use github_changelog_generator for Ember Inspector and other repos.

**Pull request closed without merging**
